// <auto-generated />
namespace Project.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcommnetstotasks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcommnetstotasks));
        
        string IMigrationMetadata.Id
        {
            get { return "201707282135582_add-commnets-to-tasks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
